services:
  - type: web
    name: csd-scanner-api
    env: python
    region: oregon # or change to your preferred region
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 10000 # Render will override this if needed
    autoDeploy: true
    runtime: python3
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - model/*
        - render.yaml
        - images/
